language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
  - bundle exec rake db:migrate
cache: bundler
env:
  matrix:
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
rvm:
  - 2.3.0
matrix:
  include:
    # Latest compiled version in http://rubies.travis-ci.org
    - rvm: 2.3.0
  allow_failures:
    - rvm: ruby-head


addons:
  postgresql: "9.4"
